\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Chapter 8 - Introduction to Linear Regression},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Chapter 8 - Introduction to Linear Regression}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  
\usepackage{geometry}
\usepackage{multicol}
\usepackage{multirow}
\usepackage{xcolor}

\begin{document}
\maketitle

\textbf{Nutrition at Starbucks, Part I.} (8.22, p.~326) The scatterplot
below shows the relationship between the number of calories and amount
of carbohydrates (in grams) Starbucks food menu items contain. Since
Starbucks only lists the number of calories on the display items, we are
interested in predicting the amount of carbs a menu item has based on
its calorie content.

\includegraphics[width=0.33\linewidth]{Homework8_files/figure-latex/unnamed-chunk-1-1}
\includegraphics[width=0.33\linewidth]{Homework8_files/figure-latex/unnamed-chunk-1-2}
\includegraphics[width=0.33\linewidth]{Homework8_files/figure-latex/unnamed-chunk-1-3}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\item
  Describe the relationship between number of calories and amount of
  carbohydrates (in grams) that Starbucks food menu items contain.

\begin{verbatim}
The relationship between the number of carolies and the amount of carbohydrtes (in grams) that starbucks food menu items contain is linear as evidenced by graph above.
\end{verbatim}
\item
  In this scenario, what are the explanatory and response variables?

\begin{verbatim}
Carbs are the explanatory variable and carolies the response variable.
\end{verbatim}
\item
  Why might we want to fit a regression line to these data?

\begin{verbatim}
We could fit a regression line to these data to see if we could find a relationship.
\end{verbatim}
\item
  Do these data meet the conditions required for fitting a least squares
  line?

\begin{verbatim}
a. The histogram of residual seems normal.
b. we asssume the data to be independent.
c. the scatter plot shows a linear relationship between carbs and carolies, and 
d. There seem to be constant variability amont the variables
\end{verbatim}
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\clearpage

\textbf{Body measurements, Part I.} (8.13, p.~316) Researchers studying
anthropometry collected body girth measurements and skeletal diameter
measurements, as well as age, weight, height and gender for 507
physically active individuals.19 The scatterplot below shows the
relationship between height and shoulder girth (over deltoid muscles),
both measured in centimeters.

\begin{center}

\includegraphics[width=0.5\linewidth]{Homework8_files/figure-latex/unnamed-chunk-2-1} 
\end{center}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\item
  Describe the relationship between shoulder girth and height. 190

\begin{verbatim}
AS shoulder girth increases so does height. This reflects the positive relationship between the two.
\end{verbatim}
\item
  How would the relationship change if shoulder girth was measured in
  inches while the units of height re- mained in centimeters?

\begin{verbatim}
The positive relationship would be maintained, and the slope would become more linear.
\end{verbatim}
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\clearpage

\textbf{Body measurements, Part III.} (8.24, p.~326) Exercise above
introduces data on shoulder girth and height of a group of individuals.
The mean shoulder girth is 107.20 cm with a standard deviation of 10.37
cm. The mean height is 171.14 cm with a standard deviation of 9.41 cm.
The correlation between height and shoulder girth is 0.67.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\item
  Write the equation of the regression line for predicting height.

\begin{verbatim}
yˆ = β0 + β1 * x

β1 = Sy/Sx * R
\end{verbatim}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{s_y <-}\StringTok{ }\FloatTok{9.41}
\NormalTok{s_x <-}\StringTok{ }\FloatTok{10.37}
\NormalTok{r <-}\StringTok{ }\FloatTok{0.67}
\NormalTok{y_mean <-}\StringTok{ }\FloatTok{171.14}
\NormalTok{x_mean <-}\StringTok{ }\FloatTok{107.20}
\NormalTok{beta1 <-}\StringTok{ }\NormalTok{(s_y }\OperatorTok{/}\StringTok{ }\NormalTok{s_x ) }\OperatorTok{*}\NormalTok{r}
\NormalTok{beta0 <-}\StringTok{ }\NormalTok{y_mean }\OperatorTok{-}\StringTok{ }\NormalTok{(beta1}\OperatorTok{*}\NormalTok{x_mean)}
\KeywordTok{cat}\NormalTok{(beta0, beta1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 105.9651 0.6079749
\end{verbatim}

\begin{verbatim}
    Equation of regression line is

    yˆ = 105.9651 + 0.6079749*x
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\item
  Interpret the slope and the intercept in this context.

\begin{verbatim}
The slope represents an increase of 0.6079 in height for every inch of shoulder.
\end{verbatim}
\item
  Calculate \(R^2\) of the regression line for predicting height from
  shoulder girth, and interpret it in the context of the application.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{r_square <-}\StringTok{ }\NormalTok{r}\OperatorTok{^}\DecValTok{2}
\NormalTok{r_square}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4489
\end{verbatim}

\begin{verbatim}
    the linear model explains approximately 45% variation in height.
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  A randomly selected student from your class has a shoulder girth of
  100 cm. Predict the height of this student using the model.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ht <-}\StringTok{ }\FloatTok{105.9651} \OperatorTok{+}\StringTok{ }\FloatTok{0.6079749}\OperatorTok{*}\DecValTok{100}
\NormalTok{ht}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 166.7626
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
  The student from part (d) is 160 cm tall. Calculate the residual, and
  explain what this residual means.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res <-}\StringTok{ }\DecValTok{160} \OperatorTok{-}\StringTok{ }\NormalTok{ht}
\NormalTok{res}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -6.76259
\end{verbatim}

\begin{verbatim}
    The negativity is an indication that the model overestimates the height data.
    
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{5}
\item
  A one year old has a shoulder girth of 56 cm. Would it be appropriate
  to use this linear model to predict the height of this child?

\begin{verbatim}
The shoulder girth of 56cm is outside of the model paramenters and might not be appropriate for estimatiom of the childs height.
\end{verbatim}
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\clearpage

\textbf{Cats, Part I.} (8.26, p.~327) The following regression output is
for predicting the heart weight (in g) of cats from their body weight
(in kg). The coefficients are estimated using a dataset of 144 domestic
cats.

\begin{center}
{
\begin{tabular}{rrrrr}
    \hline
            & Estimate  & Std. Error    & t value   & Pr($>$$|$t$|$) \\ 
    \hline
(Intercept) & -0.357    & 0.692         & -0.515    & 0.607 \\ 
body wt     & 4.034     & 0.250         & 16.119    & 0.000 \\ 
    \hline
\end{tabular} \ \\
$s = 1.452 \qquad R^2 = 64.66\% \qquad R^2_{adj} = 64.41\%$ 
}
\end{center}

\begin{center}

\includegraphics[width=0.5\linewidth]{Homework8_files/figure-latex/unnamed-chunk-7-1} 
\end{center}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  Write out the linear model.
\end{enumerate}

yˆ = -0.357 + 4.034 * x

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\item
  Interpret the intercept.

\begin{verbatim}
This indicates teh heart weight if body was zero, however the negative weight interpretetion would be misleading, thus this is just the anchor to the regressionline.
\end{verbatim}
\item
  Interpret the slope.

\begin{verbatim}
This indicates an increase of 4.034 units of heart weight for every one unit increase in body weight.
\end{verbatim}
\item
  Interpret \(R^2\).

\begin{verbatim}
64.41% of height variability can be explained by body weight.
\end{verbatim}
\item
  Calculate the correlation coefficient.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rsquare1 <-}\StringTok{ }\FloatTok{0.6466}
\NormalTok{corr1 <-}\StringTok{ }\KeywordTok{sqrt}\NormalTok{(rsquare1 )}

\NormalTok{corr1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8041144
\end{verbatim}

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\clearpage

\textbf{Rate my professor.} (8.44, p.~340) Many college courses conclude
by giving students the opportunity to evaluate the course and the
instructor anonymously. However, the use of these student evaluations as
an indicator of course quality and teaching effectiveness is often
criticized because these measures may reflect the influence of
non-teaching related characteristics, such as the physical appearance of
the instructor. Researchers at University of Texas, Austin collected
data on teaching evaluation score (higher score means better) and
standardized beauty score (a score of 0 means average, negative score
means below average, and a positive score means above average) for a
sample of 463 professors. The scatterplot below shows the relationship
between these variables, and also provided is a regression output for
predicting teaching evaluation score from beauty score.

\begin{center}
\begin{tabular}{rrrrr}
    \hline
            & Estimate  & Std. Error    & t value   & Pr($>$$|$t$|$) \\ 
  \hline
(Intercept) & 4.010     & 0.0255        &   157.21  & 0.0000 \\ 
beauty      &  \fbox{\textcolor{white}{{ Cell 1}}}  
                        & 0.0322        & 4.13      & 0.0000\vspace{0.8mm} \\ 
   \hline
\end{tabular}



\includegraphics[width=0.5\linewidth]{Homework8_files/figure-latex/unnamed-chunk-9-1} 
\end{center}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\item
  Given that the average standardized beauty score is -0.0883 and
  average teaching evaluation score is 3.9983, calculate the slope.
  Alternatively, the slope may be computed using just the information
  provided in the model summary table.

\begin{verbatim}
yˆ  = β0 + β1 * x
\end{verbatim}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{slope <-}\StringTok{ }\NormalTok{(}\FloatTok{4.010} \OperatorTok{-}\StringTok{ }\FloatTok{3.9983}\NormalTok{) }\OperatorTok{/}\StringTok{ }\FloatTok{0.0883}
\NormalTok{slope}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1325028
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\item
  Do these data provide convincing evidence that the slope of the
  relationship between teaching evaluation and beauty is positive?
  Explain your reasoning.

\begin{verbatim}
β1 = Sy/Sx * R

Since both Sy and Sx are positivethe data slope is positive as well.
\end{verbatim}
\item
  List the conditions required for linear regression and check if each
  one is satisfied for this model based on the following diagnostic
  plots.

\begin{verbatim}
Constant variability: The residual scatterplot indicates constant variability.

Independent observations: We assume data is independent in the sample.

Nearly normal residuals: The residuals histogram shows the data as nearly normally           distributed.

Linearity: The scatter plots show the relationship between beauty and teaching               evaluation as lonear.
\end{verbatim}
\end{enumerate}

\includegraphics[width=0.5\linewidth]{Homework8_files/figure-latex/unnamed-chunk-11-1}
\includegraphics[width=0.5\linewidth]{Homework8_files/figure-latex/unnamed-chunk-11-2}
\includegraphics[width=0.5\linewidth]{Homework8_files/figure-latex/unnamed-chunk-11-3}
\includegraphics[width=0.5\linewidth]{Homework8_files/figure-latex/unnamed-chunk-11-4}


\end{document}
